services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.7
    env_file:
      - .env
    volumes:
      - ./${WORK_DIR}:/src
      - ~/.aws:/root/.aws:ro
    working_dir: /src
    tty: true
