services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.7
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./${WORK_DIR}:/src
      - ~/.aws:/root/.aws:ro
    working_dir: /src
